const classData = [
  {
    Classname: "Matemáticas",
    ClassCode: "MM-101",
    students: 20,
    average: 85,
    listActivities: 3,
    totalActivities: 5,
    nextActivity: "Examen Final",
    nextActivityDate: "2023-12-01",
  },
  {
    Classname: "Historia",
    ClassCode: "HS-201",
    students: 18,
    average: 78,
    listActivities: 4,
    totalActivities: 6,
    nextActivity: "Ensayo sobre la Revolución",
    nextActivityDate: "2023-11-25",
  },
  {
    Classname: "Física",
    ClassCode: "PH-301",
    students: 22,
    average: 82,
    listActivities: 5,
    totalActivities: 7,
    nextActivity: "Práctica de Laboratorio",
    nextActivityDate: "2023-11-30",
  },
  {
    Classname: "Química",
    ClassCode: "CH-401",
    students: 19,
    average: 80,
    listActivities: 3,
    totalActivities: 6,
    nextActivity: "Tarea sobre enlaces químicos",
    nextActivityDate: "2023-11-28",
  },
  {
    Classname: "Literatura",
    ClassCode: "LT-501",
    students: 25,
    average: 88,
    listActivities: 2,
    totalActivities: 5,
    nextActivity: "Análisis de Don Quijote",
    nextActivityDate: "2023-12-02",
  },
  {
    Classname: "Inglés",
    ClassCode: "EN-101",
    students: 30,
    average: 90,
    listActivities: 6,
    totalActivities: 8,
    nextActivity: "Presentación Oral",
    nextActivityDate: "2023-12-05",
  },
  {
    Classname: "Arte",
    ClassCode: "AR-601",
    students: 15,
    average: 92,
    listActivities: 4,
    totalActivities: 6,
    nextActivity: "Proyecto de Pintura",
    nextActivityDate: "2023-12-08",
  },
  {
    Classname: "Música",
    ClassCode: "MU-701",
    students: 17,
    average: 87,
    listActivities: 3,
    totalActivities: 5,
    nextActivity: "Recital de Cierre",
    nextActivityDate: "2023-12-10",
  },
  {
    Classname: "Biología",
    ClassCode: "BI-801",
    students: 21,
    average: 83,
    listActivities: 5,
    totalActivities: 7,
    nextActivity: "Reporte de Ecosistemas",
    nextActivityDate: "2023-12-12",
  },
  {
    Classname: "Computación",
    ClassCode: "CS-901",
    students: 28,
    average: 95,
    listActivities: 7,
    totalActivities: 9,
    nextActivity: "Proyecto Final de Programación",
    nextActivityDate: "2023-12-15",
  },
];

export default classData;
